### PR TITLE
Fix: Use correct starting range and loc for JSXText tokens (fixes #227)

### LINKED ISSUE #227: Linting JSX const without brackets / parenthesis causes eslint to hang
**What version of TypeScript are you using?**
2.2.1

**What version of `typescript-eslint-parser` are you using?**
2.1.0

**What code were you trying to parse?**

```
const menuItems = <div className={theme['header__menu-items']}>
        <Icon handleClick={handleIconClick} type={IconTypes.Chat} />
        <Icon handleClick={handleIconClick} type={IconTypes.Menu} />
    </div>;
```

**What did you expect to happen?**
eslint to run successfully

**What happened?**
eslint hangs and becomes unresponsive. I've left it to run over lunch and it was still stuck.

Changing the syntax to be contained within brackets / parenthesis fixes the issue.

```
const menuItems = (
    <div className={theme['header__menu-items']}>
        <Icon handleClick={handleIconClick} type={IconTypes.Chat} />
        <Icon handleClick={handleIconClick} type={IconTypes.Menu} />
    </div>
);
```

 I've now been able to reproduce this several times.

### PR DESCRIPTION
**Pull request by soda0289**
We used to use the method `getStart()` to calculate the starting range for JSXText tokens. This would skip over whitespace and cause the value of these tokens to be empty. This would also result in the range and starting line number and column to be incorrect. This commit uses the method `getFullStart()`, on JSXText tokens, which does not skip over whitespace and allows for the correct range, value and loc to be set.

This also fixes issues with JSX indentation in the new indent rule and in the eslint-plugin-react.

### CODE REVIEW

File: lib/node-utils.js [hunk 1]
```diff
@@ -588,15 +588,16 @@ function getTokenType(token) {
  * @returns {ESTreeToken}       the converted ESTreeToken
  */
 function convertToken(token, ast) {
-    const start = token.getStart(),
+    const start = (token.kind === SyntaxKind.JsxText) ? token.getFullStart() : token.getStart(),
+        end = token.getEnd(),
         value = ast.text.slice(start, token.end),
```
Comment (JamesHenry) [inline lib/node-utils.js]: All the other references to `token.end` were updated to the variable `end`, but not this one. Just checking that is intended/not significant?

Comment (soda0289) [inline lib/node-utils.js]: I was reading through the code of typescript and noticed this method. I thought it looked a little cleaner since we use methods to access the starting point.

These are the methods to access token positions:
 - `getFullStart()` is the same as `.pos`
 - `getEnd()` is the same as `.end`
 - `getStart()` is the same as `.pos` but skipping over trivia and white space

If you want I can change the logic to use the properties to be more consistent with the rest of the code.
