### PR TITLE
Only warn about an unsupported TypeScript version once

### LINKED ISSUE #348: When using an unsupported TypeScript version, the console gets spammed with warning messages
**What version of TypeScript are you using?**
2.4.1

**What version of `typescript-eslint-parser` are you using?**
4.0.0

**What code were you trying to parse?**

A project with lots of files

**What did you expect to happen?**

```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-eslint-parser.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: ~2.3.2

YOUR TYPESCRIPT VERSION: 2.4.1

Please only submit bug reports when using the officially supported version.

=============
```

**What happened?**

```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-eslint-parser.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: ~2.3.2

YOUR TYPESCRIPT VERSION: 2.4.1

Please only submit bug reports when using the officially supported version.

=============
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-eslint-parser.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: ~2.3.2

YOUR TYPESCRIPT VERSION: 2.4.1

Please only submit bug reports when using the officially supported version.

=============
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-eslint-parser.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: ~2.3.2

YOUR TYPESCRIPT VERSION: 2.4.1

Please only submit bug reports when using the officially supported version.

=============
```
(You get the idea)

### PR DESCRIPTION
**Pull request by j-f1**
It gets annoying when you’re trying to lint a project with lots of files. Fixes #348.

### CODE REVIEW

**Comment by soda0289** [comment]
I think we can move the warning text outside the `parse()` that should eliminate the use of a global variable

**Comment by j-f1** [comment]
@soda0289 Done!

**Comment by soda0289** [comment]
@j-f1
 Thanks for making the change but on a second look I noticed we need to have access to the extra.log() and dont think this should be outside parse(). That was added since we did not want to write logs when other projects that use this parser. We still need to have the ability for users of the library to overwrite the logger.

I think we will have to use the global variable. We should move the warning text to its own function and contain the logic of checking if it has been called to there. Sorry for the confusion and thanks for the PR.

File: parser.js [hunk 1]
```diff
@@ -99,11 +100,14 @@ function parse(code, options) {
          */
         if (typeof options.loggerFn === "function") {
             extra.log = options.loggerFn;
+        } else if (options.loggerFn === false) {
+            /** */ // eslint-disable-line valid-jsdoc
```
Comment (JamesHenry) [inline parser.js]: This is a bit odd 😄  Why not put the `// eslint-disable-line valid-jsdoc` on the line you are disabling? Alternatively you could use `Function.prototype` as the value of the noop

Comment (j-f1) [inline parser.js]: If I don’t add the JSDoc comment, it errors at line 98 instead. I’ll switch to `Function.prototype`.

**Comment by JamesHenry** [comment]
Thanks a lot for this @j-f1!
