### PR TITLE
Fix: Optimize convertTokens, treat JsxText as token (fixes #70)

### LINKED ISSUE #70: Known Issue with JsxText nodes and whitespace (bug in ts.findNextToken() in tsc)
First off, thanks for creating this! I'm reeeaaally looking forward to being able to use ESLint with TypeScript!

**What version of TypeScript are you using?**
1.8.10

**What version of `typescript-eslint-parser` are you using?**
0.1.3

**What code were you trying to parse?**

```
const x = (
  <form>
    <div className={styles.separator}></div>
  </form>
);
```

**What did you expect to happen?**
It shouldn't throw an error.

**What happened?**

```
eslint --debug C:/path/to/my/file.tsx

  eslint:cli Running on files +0ms
  eslint:ignored-paths Looking for ignore file in C:\Dev+31ms
  eslint:ignored-paths Loaded ignore file C:\Dev\.eslintignore +16ms
  eslint:ignored-paths Adding C:\Dev\.eslintignore +0ms
  eslint:glob-util Creating list of files to process. +0ms
  eslint:cli-engine Processing C:/path/to/my/file.tsx +0ms
  eslint:cli-engine Linting C:/path/to/my/file.tsx +0ms
  eslint:config Constructing config for C:/path/to/my/file.tsx +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading C:\Dev\.eslintrc +0ms
  eslint:config-file Loading config file: C:\Dev\.eslintrc +16ms
  eslint:config Using C:\Dev\.eslintrc +203ms
  eslint:config Merging command line environment settings +0ms
  eslint:config-ops Apply environment settings to config +0ms
  eslint:config-ops Creating config for environment browser +0ms
  eslint:config-ops Creating config for environment es6 +0ms
Cannot read property 'range' of undefined
TypeError: Cannot read property 'range' of undefined
    at lastTokenIndex (C:\Dev\node_modules\eslint\lib\token-store.js:41:25)
    at SourceCode.api.getTokenAfter (C:\Dev\node_modules\eslint\lib\token-store.js:114:23)
    at EventEmitter.api.(anonymous function) [as getTokenAfter] (C:\Dev\node_modules\eslint\lib\eslint.js:1033:48)
    at RuleContext.(anonymous function) [as getTokenAfter] (C:\Dev\node_modules\eslint\lib\rule-context.js:155:33)
    at EventEmitter.validateBraceSpacing (C:\Dev\node_modules\eslint-plugin-react\lib\rules\jsx-curly-spacing.js:194:28)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (C:\Dev\node_modules\eslint\lib\util\node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (C:\Dev\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (C:\Dev\node_modules\eslint\lib\util\comment-event-generator.js:97:23)
```

### PR DESCRIPTION
**Pull request by JamesHenry**
**UPDATE**: I was able to use this PR to work around the long-standing issue with JsxText nodes outlined in #70 

The test case: `jsx/test-content` has been enabled.

------------

Based on feedback from the TypeScript team here: https://github.com/Microsoft/TypeScript/issues/13519#issuecomment-274662665

I will be looking into refactoring remaining occurrences of `ts.findNextToken` in future too

### CODE REVIEW

**Comment by soda0289** [comment]
Does this fix the issue with JSX? I was tracking that issue down. It's a bug in findNexToken() where it does not descend into JSX elements. I was going to submit pull request for that once I got a clean solution but this looks like it avoids it.

**Comment by JamesHenry** [comment]
No, was also hoping that, this issue is still present on this branch

**Comment by soda0289** [comment]
That sucks, I guess this JSX bug runs a little deeper.
This is still a great optimization since it doesn't have to start at the top of the AST every time we find a token, like it did with findNextToken().

**Comment by JamesHenry** [comment]
@soda0289 It is, but it's a task that is only performed once, so the benefits are minimal.

I think I may have just added a solution for the JsxText issue - now that we have control over the traversal into child nodes, we can create an exception for JsxText and treat it like a token.

I am going to double check the behaviour on some JSX now and if it works I'll be converting this PR into a bug fix

**Comment by soda0289** [comment]
Hmm I think JsxText is a token.
The main examples i was test are:
```ts
<test></test>
```
```ts
<test> </test>
```

```ts
<test>
</test>
```

```ts
<test> aaa
</test>
```

**Comment by JamesHenry** [comment]
So you are agreeing with me? 😄 

I have confirmed that the parser will no longer throw errors for whitespace in JsxText, going to turn this into a bug fix.

**Comment by soda0289** [comment]
Nice!! I'm very excited for JSX support!

 I thought isToken would return true for JsxText isn't that extra check unnecessary?

**Comment by soda0289** [comment]
I just checked the typescript code. In ts version 2.0 JsxText is not a token:
https://github.com/Microsoft/TypeScript/blob/release-2.0/lib/typescript.d.ts#L283
In ts master it is a token:
https://github.com/Microsoft/TypeScript/blob/master/lib/typescript.d.ts#L50

**Comment by JamesHenry** [comment]
Was just replying that they do not classify it as a token 😄  Nice digging though! We can remove that extra check in the 2.2 branch probably, but it will not do any harm

**Comment by JamesHenry** [comment]
Updated the description, this is now ready for review.

File: lib/ast-converter.js [hunk 1]
```diff
@@ -256,6 +256,26 @@ function fixExports(node, result, ast) {
 }
 
 /**
+ * Returns true if a given TSNode is a token
+ * @param  {TSNode} node the TSNode
+ * @returns {boolean}     is a token
+ */
+function isToken(node) {
+     /**
+     * Note: We treat JsxText like a token (TypeScript doesn't classify it as one),
```
Comment (DanielRosenwasser) [inline lib/ast-converter.js]: This sounds like a bug on us. I vaguely recall trying to fix this months ago but it was not a simple fix.

**Comment by DanielRosenwasser** [comment]
👍

File: lib/ast-converter.js (hunk 1 above)
Comment (JamesHenry) [inline lib/ast-converter.js]: Interesting, and thanks for keeping an eye on the project @DanielRosenwasser 😄 

I will take another look at this once TypeScript 2.2 hits stable.

**Comment by JamesHenry** [comment]
Throwing this open for anyone on @eslint/eslint-team to do a final review. I think this should be pretty safe to merge

File: lib/ast-converter.js (hunk 1 above)
Comment (JamesHenry) [inline lib/ast-converter.js]: @DanielRosenwasser just FYI this does indeed work as of TS 2.2!

I am removing this extra check in the PR to support 2.2 -> #169
