### PR TITLE
Fix: Remove all tokens inside comments from tokens array (fixes #422)

### LINKED ISSUE #422: Core indent rule reports false positives in doc blocks
**What version of TypeScript are you using?**
`typescript@2.6.2`

**What version of `typescript-eslint-parser` are you using?**
`typescript-eslint-parser@11.0.0`

**What code were you trying to parse?**

```ts
/**
 * This is a function.
 * @param {String} text
 * @returns {String}
 */
function foo(text: string): string {}

```

The minimal repro case is:
```ts
/**
 * This is a function.
 * @param {String} text
 * @returns {String}
 */
function foo() {}
```

Running the autofixer generates the following code (which then passes):
```ts
 /**
 * This is a function.
{String} text
{String}
 */
function foo(text: string): string {}
```

**What did you expect to happen?**
No errors! This only occurs with the typescript-eslint-parser. It does not happen with the default parser.

**What happened?**
```sh
/Users/cataldo/Code/test/eslint-test/index.js
  3:1  error  Expected indentation of 0 spaces but found 3  indent
  4:1  error  Expected indentation of 0 spaces but found 3  indent
```

I'll try to look into the cause if I get a chance, but not sure if and when that'll be. Took the bug label off because I'm not sure what the established practice is in this repo - happy to update though :)

### PR DESCRIPTION
**Pull request by kaicataldo**
This fixes an issue where TypeScript generates tokens for `{Type}` (for both the brackets and the Identifier `Type`), causing the indent rule in core to have some false positives. I'm assuming these tokens are generated as part of TypeScript's JS file checking and type hinting from doc blocks.

@eslint/eslint-team As an aside, could we potentially leverage this behavior for our own JSDoc parsing and validation in ESLint core? Would be nice if we could rely on a well-maintained project like TypeScript instead of doctrine, since we've been struggling to maintain that.

Maybe @JamesHenry has some idea of the feasibility of this, given your experience!

This is my first time working with this codebase or really anything TypeScript related, so please do let me know if there are better ways to achieve this or if any assumptions I've made are incorrect.

To illustrate the change, here's a before and after of the tokens and comments arrays generated for the following code:

```js
/**
 * This is a function.
 * @param {String} text
 * @returns {String}
 */
function foo(text) {}
```
Before this patch:
```
Tokens:  [ { type: 'Punctuator',
    value: '{',
    range: [ 37, 38 ],
    loc: { start: [Object], end: [Object] } },
  { type: 'Identifier',
    value: 'String',
    range: [ 38, 44 ],
    loc: { start: [Object], end: [Object] } },
  { type: 'Punctuator',
    value: '}',
    range: [ 44, 45 ],
    loc: { start: [Object], end: [Object] } },
  { type: 'Identifier',
    value: 'text',
    range: [ 46, 50 ],
    loc: { start: [Object], end: [Object] } },
  { type: 'Punctuator',
    value: '{',
    range: [ 63, 64 ],
    loc: { start: [Object], end: [Object] } },
  { type: 'Identifier',
    value: 'String',
    range: [ 64, 70 ],
    loc: { start: [Object], end: [Object] } },
  { type: 'Punctuator',
    value: '}',
    range: [ 70, 71 ],
    loc: { start: [Object], end: [Object] } },
  { type: 'Keyword',
    value: 'function',
    range: [ 76, 84 ],
    loc: { start: [Object], end: [Object] } },
  { type: 'Identifier',
    value: 'foo',
    range: [ 85, 88 ],
    loc: { start: [Object], end: [Object] } },
  { type: 'Punctuator',
    value: '(',
    range: [ 88, 89 ],
    loc: { start: [Object], end: [Object] } },
  { type: 'Identifier',
    value: 'text',
    range: [ 89, 93 ],
    loc: { start: [Object], end: [Object] } },
  { type: 'Punctuator',
    value: ')',
    range: [ 93, 94 ],
    loc: { start: [Object], end: [Object] } },
  { type: 'Punctuator',
    value: '{',
    range: [ 95, 96 ],
    loc: { start: [Object], end: [Object] } },
  { type: 'Punctuator',
    value: '}',
    range: [ 96, 97 ],
    loc: { start: [Object], end: [Object] } } ]

Comments:  [ { type: 'Block',
    value: '*\n * This is a function.\n * @param {String} text\n * @returns {String}\n ',
    range: [ 0, 75 ],
    loc: { start: [Object], end: [Object] } } ]
```

After this patch:
```
Tokens:  [ { type: 'Keyword',
    value: 'function',
    range: [ 76, 84 ],
    loc: { start: [Object], end: [Object] } },
  { type: 'Identifier',
    value: 'foo',
    range: [ 85, 88 ],
    loc: { start: [Object], end: [Object] } },
  { type: 'Punctuator',
    value: '(',
    range: [ 88, 89 ],
    loc: { start: [Object], end: [Object] } },
  { type: 'Identifier',
    value: 'text',
    range: [ 89, 93 ],
    loc: { start: [Object], end: [Object] } },
  { type: 'Punctuator',
    value: ')',
    range: [ 93, 94 ],
    loc: { start: [Object], end: [Object] } },
  { type: 'Punctuator',
    value: '{',
    range: [ 95, 96 ],
    loc: { start: [Object], end: [Object] } },
  { type: 'Punctuator',
    value: '}',
    range: [ 96, 97 ],
    loc: { start: [Object], end: [Object] } } ]

Comments:  [ { type: 'Block',
    value: '*\n * This is a function.\n * @param {String} text\n * @returns {String}\n ',
    range: [ 0, 75 ],
    loc: { start: [Object], end: [Object] } } ]
```

### CODE REVIEW

**Comment by j-f1** [comment]
Looks good!

Can you delete `package-lock.json.1799798656`?

File: lib/node-utils.js [hunk 1]
```diff
@@ -244,6 +244,32 @@ function isComma(token) {
...
+}
+
+/**
+ * Returns true if the given TSToken is inside a comment
+ * Non-comment type tokens are generated for types in JSDoc Blocks
+ * @param  {TSToken}  token the TypeScript token
+ * @returns {boolean}       is inside a commment
+ */
+function isInsideComment(token) {
+    if (token.kind === SyntaxKind.SourceFile) {
```
Comment (kaicataldo) [inline lib/node-utils.js]: Is this check sufficient? I was wondering if the algorithm could alternatively be:

Comment (kaicataldo) [reply lib/node-utils.js]: We could also avoid crawling up the tree on every node if we knew exactly what kind of tokens can exist in JSDoc comments (scoping the check to those node types). Maybe someone with more knowledge of could help with that?

File: lib/node-utils.js [hunk 2]
```diff
@@ -693,7 +719,7 @@ function convertTokens(ast) {
      * @returns {undefined}
      */
     function walk(node) {
```
Comment (kaicataldo) [inline lib/node-utils.js]: I also thought about keeping somehow keeping track of if the parent node is a comment and passing it through the recursive `walk` function here (it could just be a boolean flag or options object). Now that I think about it, that might actually be the best way to achieve this since we probably don't really want to be potentially crawling up the tree on every node when we don't have to.

And again, if there's a better way to tell if a node is inside a comment from some value on the AST or some util we already have, please let me know!

**Comment by kaicataldo** [comment]
@j-f1 Whoops! Not sure how that got in there. Thanks.

File: lib/node-utils.js [hunk 3]
```diff
@@ -244,6 +244,15 @@ function isComma(token) {
     return token.kind === SyntaxKind.CommaToken;
 }
 
+/**
+ * Returns true if the given TSToken is a comment
+ * @param  {TSToken}  token the TypeScript token
+ * @returns {boolean}       is commment
+ */
+function isComment(token) {
+    return (token.kind === SyntaxKind.SingleLineCommentTrivia || token.kind === SyntaxKind.MultiLineCommentTrivia) || (token.kind >= SyntaxKind.JSDocTypeExpression && token.kind <= SyntaxKind.JSDocTypeLiteral);
```
Comment (kaicataldo) [inline lib/node-utils.js]: Is this the correct check for comment tokens?

**Comment by kaicataldo** [comment]
I realized this could be simplified immensely. Since we're walking the tree from the top down, we can simply stop walking whenever we encounter a comment. This way, it's children will never be converted or added to the token list.

File: lib/node-utils.js (hunk 2 above)
Comment (kaicataldo) [reply lib/node-utils.js]: Realized there's an even simpler way to do this - please see later commits.

File: lib/node-utils.js [hunk 4]
```diff
@@ -244,6 +244,15 @@ function isComma(token) {
     return token.kind === SyntaxKind.CommaToken;
 }
 
+/**
+ * Returns true if the given TSToken is a comment
+ * @param  {TSToken}  token the TypeScript token
+ * @returns {boolean}       is commment
+ */
+function isComment(token) {
+    return token.kind === SyntaxKind.SingleLineCommentTrivia || token.kind === SyntaxKind.MultiLineCommentTrivia || (token.kind >= SyntaxKind.JSDocTypeExpression && token.kind <= SyntaxKind.JSDocTypeLiteral);
```
Comment (kaicataldo) [inline lib/node-utils.js]: Is this the correct check for comment tokens?

**Comment by kaicataldo** [comment]
Friendly ping @JamesHenry @soda0289

File: lib/node-utils.js (hunk 4 above)
Comment (JamesHenry) [reply lib/node-utils.js]: TypeScript themselves use this within their private utilities:

```ts
function isComment(kind: SyntaxKind): boolean {
  return kind === SyntaxKind.SingleLineCommentTrivia || kind === SyntaxKind.MultiLineCommentTrivia;
}
```

I feel like we should split the JSDoc checks out into a separate function.

The TypeScript team has these (again not in their public API, but useful utils):

```ts
// JSDoc
    /** True if node is of some JSDoc syntax kind. */
    /* @internal */
    export function isJSDocNode(node: Node): boolean {
        return node.kind >= SyntaxKind.FirstJSDocNode && node.kind <= SyntaxKind.LastJSDocNode;
    }

    /** True if node is of a kind that may contain comment text. */
    export function isJSDocCommentContainingNode(node: Node): boolean {
        return node.kind === SyntaxKind.JSDocComment || isJSDocTag(node);
    }

    // TODO: determine what this does before making it public.
    /* @internal */
    export function isJSDocTag(node: Node): boolean {
        return node.kind >= SyntaxKind.FirstJSDocTagNode && node.kind <= SyntaxKind.LastJSDocTagNode;
    }
```

**Comment by kaicataldo** [comment]
Updated! Thanks for the review :)

**Comment by kaicataldo** [comment]
Friendly ping!

**Comment by JamesHenry** [comment]
I think this is great for now, thanks! I'm going to change it to be a `Breaking` change though just in case anybody was depending on the old behaviour somehow

**Comment by kaicataldo** [comment]
Thanks!
