### PR TITLE
Fix: Convert MetaProperty (new.target) nodes correcly (fixes #194)

### LINKED ISSUE #194: MetaProperty nodes are not converted correctly
**What version of TypeScript are you using?**
2.2.1

**What version of `typescript-eslint-parser` are you using?**
2.0.0

**What code were you trying to parse?**

```ts
new foo.bar();
//OR
() => {
    new.target;
}
```

**What did you expect to happen?**
`new foo.bar()` should generate a NewExpression node
`new.target()` should generate a MetaProperty node

**What happened?**
They both generate invalid MetaProperty nodes

PR will be up soon

### PR DESCRIPTION
**Pull request by soda0289**
The MetaProperty node was added a couple of months ago into typescript. I think it landed in 2.2.
https://github.com/Microsoft/TypeScript/pull/12783

I have to create a identifier node for 'new' since it is not part of the typescript metaproperty node.

### CODE REVIEW

File: tests/lib/basics.js [hunk 1]
```diff
@@ -59,6 +59,9 @@ describe("basics", function() {
             try {
                 result = parser.parse(code, config);
                 result = tester.getRaw(result);
+                if (Object.keys(expected).length === 0) {
+                    console.log(JSON.stringify(result, null, 4));
+                }
```
Comment (soda0289) [inline tests/lib/basics.js]: I got to delete this. Sorry

Comment (JamesHenry) [inline tests/lib/basics.js]: Just in time 😄  I was just reviewing

**Comment by soda0289** [comment]
We have those tests already:
https://github.com/eslint/typescript-eslint-parser/tree/master/tests/fixtures/ecma-features/newTarget

I had to enable the new-target rule by removing it from the filter in tests/lib/ecma-features.js

Typescript does not throw an error you have an invalid metaproperty, such as `new.unkown_property`. I could add tests for those cases.

**Comment by JamesHenry** [comment]
Ah! Sorry, that makes sense
