### PR TITLE
Fix: Fixes linting errors (fixes #10)

### LINKED ISSUE #10: Lint script fails for various reasons
We are making progress, slowly but surely, towards getting this repo ready for active development! This issue is to track changes necessary for the project to be able to lint itself successfully.

There are currently a number of reasons why the lint script is failing, including:

- Missing semicolons
- Formatting issues
- Unused code
- Missing JSDoc blocks on existing functions

Obviously some of these things are very easy to remedy without having written any of the code, but others are not. The code which is included, but not used, is particularly difficult to reason about.

I will open a PR and look for your feedback on getting this issue resolved.

Then perhaps we can look at getting the lint script to run as a requisite of future PRs?

### PR DESCRIPTION
**Pull request by JamesHenry**
As mentioned in issue #10, there are a number of areas where I will be looking for your feedback on this one.

I have given the missing JSDoc blocks a good go, but you may want me to change the wording or description of certain parameters/return values.

If you could offer some context on the code which I have had to comment out as part of this PR (or which is already commented out) that would be great as it could expedite future development and research.

Thanks!

### CODE REVIEW

File: lib/ast-converter.js [hunk 1]
```diff
@@ -115,22 +115,47 @@ TOKEN_TO_TEXT[SyntaxKind.CaretEqualsToken] = "^=";
 TOKEN_TO_TEXT[SyntaxKind.AtToken] = "@";
 TOKEN_TO_TEXT[SyntaxKind.InKeyword] = "in";
 
+/**
+ * Returns true if the given node is a valid ESTree class member
+ * @param  {object}  node AST node
```
Comment (nzakas) [inline lib/ast-converter.js]: What I'd like to do is use `{ESTreeNode}` for anything that represents an ESTree AST node and `{TSNode}` for anything that represents a TypeScript AST node. In this case, it would be the latter.

File: lib/ast-converter.js [hunk 2]
```diff
@@ -115,22 +115,47 @@ TOKEN_TO_TEXT[SyntaxKind.CaretEqualsToken] = "^=";
...
+ * @returns {boolean}      is valid class member
+ */
 function isESTreeClassMember(node) {
     return node.kind !== SyntaxKind.PropertyDeclaration && node.kind !== SyntaxKind.SemicolonClassElement;
 }
 
+/**
+ * Returns true if the given token is a comma
+ * @param  {object}  token the syntax token
```
Comment (nzakas) [inline lib/ast-converter.js]: Similar deal here, `{ESTreeToken}` or `{TSToken}` (the latter in this case).

File: lib/ast-converter.js [hunk 3]
```diff
@@ -115,22 +115,47 @@ TOKEN_TO_TEXT[SyntaxKind.CaretEqualsToken] = "^=";
...
+ * @returns {boolean}       is comma
+ */
 function isComma(token) {
     return token.kind === SyntaxKind.CommaToken;
 }
 
+/**
+ * Returns true if the given operator is the assignment operator
+ * @param  {object}  operator the operator
```
Comment (nzakas) [inline lib/ast-converter.js]: Please use `{Object}` (uppercase O) for objects, but try to be more specific as per previous comments.

File: Makefile.js [hunk 4]
```diff
@@ -103,6 +103,10 @@ function splitCommandResultToLines(result) {
     return result.trim().split("\n");
 }
 
+/**
+ * Returns a list of sorted, valid semtantic-verisioning git tags
+ * @returns {array} The version tags
```
Comment (nzakas) [inline Makefile.js]: `{string[]}`

File: lib/ast-converter.js [hunk 5]
```diff
@@ -293,6 +353,11 @@ function convertToken(token, ast) {
     return newToken;
 }
 
+/**
+ * Converts all tokens for the given AST
+ * @param  {object} ast the AST object
+ * @returns {array}     the converted tokens
```
Comment (nzakas) [inline lib/ast-converter.js]: `{ESTreeToken[]}`

File: lib/ast-converter.js [hunk 6]
```diff
@@ -333,12 +404,21 @@ module.exports = function(ast, extra) {
             loc: getLoc(node, ast)
         };
 
+        /**
+         * Copies the result object
```
Comment (nzakas) [inline lib/ast-converter.js]: Copies the result object into an ESTree  node with just a `type` property. This is used only for leaf nodes that have no other properties.

File: lib/ast-converter.js [hunk 7]
```diff
@@ -333,12 +404,21 @@ module.exports = function(ast, extra) {
...
+         * @returns {void}
+         */
         function simplyCopy() {
             assign(result, {
                 type: SyntaxKind[node.kind]
             });
         }
 
+        /**
+         * Converts child node
```
Comment (nzakas) [inline lib/ast-converter.js]: Converts a TypeScript node into an ESTree node.

File: tests/lib/ecma-features.js [hunk 8]
```diff
@@ -41,8 +41,8 @@ var assert = require("chai").assert,
 // Setup
 //------------------------------------------------------------------------------
 
-var FIXTURES_DIR = "./tests/fixtures/ecma-features",
-    FIXTURES_MIX_DIR = "./tests/fixtures/ecma-features-mix";
+var FIXTURES_DIR = "./tests/fixtures/ecma-features";
+// var FIXTURES_MIX_DIR = "./tests/fixtures/ecma-features-mix";
```
Comment (nzakas) [inline tests/lib/ecma-features.js]: Do the tests still work with this stuff commented out?

**Comment by nzakas** [comment]
Thanks for this! The commented out `acornOptions` code I was leaving in there as a reminder to address `ecmaVersion` and comments, but it's probably not needed.

**Comment by JamesHenry** [comment]
Thanks for the notes, Nicholas! I will update the PR accordingly.

File: tests/lib/ecma-features.js (hunk 8 above)
Comment (JamesHenry) [inline tests/lib/ecma-features.js]: I didn't come in with any expectations, given the alpha version, but to be honest... nothing about this project has worked so far :smile: 

Specifically for the tests not running, the first issue is as described in https://github.com/eslint/typescript-eslint-parser/issues/6

Each PR I have submitted so far has been about trying to pick off the next lowest-hanging fruit, and, given it doesn't really require any domain-specific knowledge, fixing the linting seemed like the best choice at this stage. The tests will be my next focus.

**Comment by JamesHenry** [comment]
Updated! PTAL

**Comment by nzakas** [comment]
LGTM. Thanks!
